version: "3.8"

services:
    postgres:
        image: postgres:latest
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: dev
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"

    mongo:
        image: mongo:latest
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo
            MONGO_INITDB_ROOT_PASSWORD: mongo
        ports:
            - "27017:27017"

volumes:
    postgres-data:
        driver: local
    mongo-data:
        driver: local
